### ISSUE TITLE
Texto Duplicado na Página "Esquemas de Elementos Personalizados (Custom Element Schemas)"

### ISSUE THREAD

**Issue by davidburil** [codexrodrigues/expertsinangular.com.br#1]
O trecho de texto a seguir está duplicado na página "Esquemas de Elementos Personalizados (Custom Element Schemas)"

```
O Desafio dos Elementos Desconhecidos
Por padrão, o Angular é rigoroso com a sintaxe dos templates. Se ele encontrar um elemento HTML que não reconhece, como <meu-componente-personalizado>, ele irá gerar um erro, pois não sabe como lidar com essa tecnologia desconhecida.
```

Outra coisa que mudaria é o link para esse repositório. O link está abrindo na mesma página e tirando seu leitor do site. O ideal é abrir em outra janela ou aba.

**Comment by codexrodrigues** [comment]
Obrigado 🙂 vou corrigir

Em sex., 2 de ago. de 2024 12:37, David Buril ***@***.***>
escreveu:

**Comment by codexrodrigues** [comment]
Olá, @davidburil,

A duplicação de texto na seção "Esquemas de Elementos Personalizados (Custom Element Schemas)" foi corrigida. Também ajustamos o link para abrir em uma nova aba, conforme sua sugestão.

Agradeço pelo feedback e pela observação!

Se houver mais algo que eu possa ajudar, por favor, me avise.

Obrigado!
